version: '3.8'

services:
  database:
    image: postgres:14.0-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "45412:5432"
    networks:
      app_net:
        ipv4_address: 192.167.10.26

  webserver:
    image: nginx:1.21-alpine
    ports:
      - "8007:80"
    volumes:
      - .:/app
      - ./etc/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - app_net

  php:
    build:
      dockerfile: Dockerfile
      context: etc/docker/php
    volumes:
      - .:/app
    links:
      - database
    networks:
      - app_net
    environment:
      PHP_IDE_CONFIG: ${PHP_XDEBUG_IDE_CONFIG}

volumes:
  webserver:
  php:

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.167.10.24/27